# 定义flit包长度等的相关常量
FLIT_TEXT_LENGTH_BYTE = 8
FLIT_TEXT_NUM_BYTE = 4
FLIT_TEXT_LENGTH = FLIT_TEXT_NUM_BYTE * (FLIT_TEXT_LENGTH_BYTE + 1)
FLIT_BINARY_LENGTH_VALUE = 4
FLIT_BINARY_NUM_VALUE = 4
FLIT_BINARY_LENGTH = FLIT_BINARY_NUM_VALUE * FLIT_BINARY_LENGTH_VALUE